#!/bin/sh
# Copyright (C) 2008 ePoint Systems Ltd

. /usr/lib/epoint-fixip/lock
. /usr/lib/epoint-fixip/tariffs

ACLS=`acl_files`
WHITELIST=/etc/epoint.issuers

acl_lock

[ -e $WHITELIST ] || touch $WHITELIST
for ACL in $ACLS; do
	[ -e $ACL ] || touch $ACL
done

# ipv4 only
IPREG='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'

{
	echo "*filter"
	echo ":FIXIPFORWARD -"
	for ACL in $ACLS; do
		awk -v ip="$IPREG" '
		$1 ~ ip {
			print "-A FIXIPFORWARD -i ppp+ -s " $1 " -j ACCEPT"
			print "-A FIXIPFORWARD -o ppp+ -d " $1 " -j ACCEPT"
		}' $ACL
	done
	awk '!/^[ \t]*#/ && NF > 0 {
		print "-A FIXIPFORWARD -p tcp -i ppp+ -d " $1 " -j ACCEPT"
		print "-A FIXIPFORWARD -p tcp -o ppp+ -s " $1 " -j ACCEPT"
	}' $WHITELIST
	echo "COMMIT"
} | /usr/sbin/iptables-restore --noflush

{
	echo "*nat"
	echo ":FIXIPDNAT -"
	echo ":FIXIPSNAT -"
	for ACL in $ACLS; do
		awk -v ip="$IPREG" '
		$1 ~ ip {
			print "-A FIXIPDNAT -s " $1 " -j ACCEPT"
			print "-A FIXIPSNAT -s " $1 " -j ACCEPT"
		}' $ACL
	done
#	awk '!/^[ \t]*#/ && NF > 0 {
#		print "-A FIXIPDNAT -p tcp -d " $1 " -j ACCEPT"
#	}' $WHITELIST
	echo "COMMIT"
} | /usr/sbin/iptables-restore --noflush

acl_unlock
